name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: deploy_on_vercel
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Debug - Vérifier la structure du repo
        run: ls -al
        working-directory: App  # ✅ Vérifie si "App/" contient bien les fichiers du projet

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Install Dependencies
        run: npm install
        working-directory: App  # ✅ On installe bien dans App/

      - name: Build Project
        run: npm run build
       

      - name: Debug - Vérifier le contenu du build
        run: ls -al
        

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        

      - name: Deploy Project Artifacts to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        
